bin/mink-test-server
composer.json
tests/AbstractConfig.php

I wrote it in bash for now, as it is very easy. It should work on windows when using Cygwin or GitBash (but I have not tried it yet).
I could have written it in PHP, but it would have been much more complex (launching a subprocess on PHP in a cross-platform way is not that simple, which is why Symfony has a component dedicated to that task)

Add a script to launch a webserver for fixtures easily

---

bin/mink-test-server

This is necessary to be able to use this script for the ZombieDriver testsuite on Travis. The goal is to force PHP to bin on IPv4, as zombie.js and PHP seem to have a different resolution for localhost on Travis (locally, I have no issue, as localhost resolves first to ipv4. But Travis resolves first to IPv6 except that Zombie.js will use IPv4)

Make the host configurable when running the server

---

composer.json
http-kernel-fixtures/404.php
http-kernel-fixtures/500.php
http-kernel-fixtures/advanced_form_post.php
http-kernel-fixtures/basic_auth.php
http-kernel-fixtures/basic_form_post.php
http-kernel-fixtures/basic_get_form.php
http-kernel-fixtures/cookie_page1.php
http-kernel-fixtures/cookie_page2.php
http-kernel-fixtures/cookie_page3.php
http-kernel-fixtures/headers.php
http-kernel-fixtures/issue130.php
http-kernel-fixtures/issue140.php
http-kernel-fixtures/print_cookies.php
http-kernel-fixtures/redirector.php
http-kernel-fixtures/response_headers.php
http-kernel-fixtures/session_test.php
http-kernel-fixtures/sub-folder/cookie_page1.php
http-kernel-fixtures/sub-folder/cookie_page2.php
src/FixturesKernel.php

This is meant to replace the Silex app used by BrowserKitDriver. This uses a minimalist implementation of the kernel, while still keeping support for sessions as our tests need it.
Fixtures files are copied from BrowserKitDriver, simply replacing the way to access the request.
Using HttpKernel directly rather than the full Silex allows to limit the needed dependencies (much easier to maintain, as they should stay optional dependencies as most drivers don't need it when running tests).

Add an HttpKernel implementation exposing fixtures

---

tests/Form/Html5Test.php
web-fixtures/html5_form.html

Currently MinkBrowserKit does not support the formaction / formmethod html5 attributes that control submission of the form depending on the clicked button. They are [supported by all modern browsers](http://caniuse.com/#search=formaction).
This PR adds tests to go with the bugfix committed to the BrowserKit driver separately.

Add tests for handling of HTML5 formaction and formmethod

---

http-kernel-fixtures/404.php
http-kernel-fixtures/advanced_form_post.php
http-kernel-fixtures/headers.php
http-kernel-fixtures/print_cookies.php
tests/AbstractConfig.php
tests/Basic/CookieTest.php
tests/Basic/HeaderTest.php
tests/Basic/StatusCodeTest.php
tests/Form/GeneralTest.php
tests/Form/Html5Test.php
tests/Form/SelectTest.php
tests/Js/WindowTest.php
tests/SkippingUnsupportedTestCase.php
tests/TestCase.php
web-fixtures/404.php
web-fixtures/advanced_form_post.php
web-fixtures/headers.php
web-fixtures/print_cookies.php
web-fixtures/utils.php

This avoids cases where we dump ``>`` and ``'`` without escaping. Escaping is now performed cleanly on the whole outputted string.
To simplify assertions, the dumping is performed in a custom format instead of using ``print_r`` and ``var_export``, to avoid using ``'`` and ``>`` in the boilerplate of the dump (or any other char being escaped).
Tests are passing for BrowserKit, Goutte and Zombie. Selenium2Driver fails, but with the same failure than before this change, so it needs to be debugged separately.
This refactoring will help the third-party PhantomJS driver to run the unmodified testsuite (they currently replace all these tests, because PhantomJS gives them the escaped chars when it parses the HTML containing chars which should have been escaped but are not).

Escape HTML properly when exporting values

---

tests/Form/SelectTest.php

Having data provider methods starting with "test" will make PHPUnit consider them as tests. This has the following effects:
- method is called more then once, depending on the code it might cause issues
- PHPUnit in strict mode will complain that the data provider method does not do any assertions

Corrected data provider name

---

tests/Form/RadioTest.php
tests/TestCase.php

`checkRequirements` was not an official extension point, and became private in PHPUnit 7

Fix compatibility with PHPUnit 7

---

http-kernel-fixtures/cookie_page1.php
http-kernel-fixtures/cookie_page3.php
http-kernel-fixtures/issue140.php
http-kernel-fixtures/sub-folder/cookie_page1.php
src/FixturesKernel.php

Fixes deprecation from latest Symfony version
```
The default value of the "$secure" and "$samesite" arguments of "Symfony\Component\HttpFoundation\Cookie::__construct"'s constructor will respectively change from "false" to "null" and from "null" to "lax" in Symfony 5.0, you should define their values explicitly or use "Cookie::create()" instead.
```
Supports both current (constructor) version and suggested `Cookie::create` factory.
Since supported PHP version is 5.3.x+, couldn't use `Cookie::class` constant so instead used string of class name.

Fix legacy cookie defaults deprecations

---

tests/Js/ChangeEventTest.php

While working on https://github.com/minkphp/MinkSelenium2Driver/pull/304 noticed that `testSetValueChangeEvent` set "text" into `<input type=file/>`, but does not accept simple text, it only accepts a filename.

improving testSetValueChangeEvent

---

README.md
composer.json

Until now, our CI config relies on the simple-phpunit script of the symfony/phpunit-bridge to install a version of PHPUnit compatible with the PHP version. But this has one drawback: the bridge could be updated to select new PHPUnit versions before our testsuite is compatible.
So we now use a composer dependency directly.
Forcing a PHPUnit version in the bridge would be hard, as we cannot have a single version supported by all PHP versions. That's why this solution was selected.

Add PHPUnit as a dependency

---

tests/Form/GeneralTest.php

...cause both pages have a title and we are on the new/submitted page if title is "Advanced form save".
Form page: https://github.com/minkphp/driver-testsuite/blob/d208035ccc5eaf4f1def0299a1979c1851a9a0fb/web-fixtures/advanced_form.html#L4
Submitted page: https://github.com/minkphp/driver-testsuite/blob/d208035ccc5eaf4f1def0299a1979c1851a9a0fb/web-fixtures/advanced_form_post.php#L4
Edit: Added file preview.

Fix condition for safePageWait in GeneralTest::testAdvancedForm

---

http-kernel-fixtures/sub-folder/cookie_page4.php
tests/Basic/CookieTest.php
web-fixtures/sub-folder/cookie_page4.php

The previous tests only ensured that a root cookie removed in a
subfolder was applied to the child folder. It did not check that a
cookie set only in a folder is correctly deleted.
This patch adds a new test for a cookie which is set with a $path
argument other than /.
See https://github.com/minkphp/MinkBrowserKitDriver/pull/157 for an example of this issue.

Add test for removal of cookie in a subpath

---

web-fixtures/cookie_page1.php
web-fixtures/cookie_page3.php
web-fixtures/issue140.php

According to https://www.php.net/manual/en/function.setcookie.php third param of setcookie has to be of type ```int``` and fourth param has to be of type ```string```. This leads at least in ```robertfausk/mink-panther-driver``` with ```PHP 8.1``` to failing tests.

Fix: Use correct data type when calling method setcookie()

---

src/FixturesKernel.php

This is opting out of the return type deprecation instead of adding the native return type (which will be necessary for the Symfony 6 support). This is done because adding the return type requires using PHP 7.2+, and I'm not yet done with bumping the min version.

Add support for Symfony 5 in the fixtures kernel

---

composer.json
http-kernel-fixtures/cookie_page1.php
http-kernel-fixtures/cookie_page3.php
http-kernel-fixtures/issue140.php
http-kernel-fixtures/sub-folder/cookie_page1.php
http-kernel-fixtures/sub-folder/cookie_page4.php
src/FixturesKernel.php

This also declares the proper dependencies (including a conflict rule to enforce the supported version of the Symfony components used by the kernel-based fixtures when used by drivers)

Add support for Symfony 6 and drop Symfony <4.4

---

web-fixtures/sub-folder/cookie_page4.php

See https://www.php.net/manual/en/function.setcookie.php - passing a boolean here as the third of >3 parameters triggers warning in output on PHP8.1 (which prevents cookie getting set and breaks cookie tests for me).
It's also valid post 7.3 to pass an array as the third parameter. From 8.1 passing other types (eg `null` in this instance) emits a deprecation notice, and this usage will fail from 9.0.
To reproduce using minkphp/MinkGoutteDriver and PHP8.1
- `git clone git@github.com:minkphp/MinkGoutteDriver`
- `cd MinkGoutteDriver`
- `docker run --rm -ti -v $(pwd):/code composer bash` (currently this is PHP8.1)
- start `./vendor/bin/mink-test-server` (I used a separate `docker exec... bash` on the same container to do this)
- `./vendor/bin/phpunit` (output below)
- `curl -s …

`setcookie()` expires_or_options param is integer not mixed

---

web-fixtures/js_test.html

`event.which` is obsolete and not even set in some browsers nor set by the latest syn.js
needed for https://github.com/minkphp/MinkSelenium2Driver/pull/358 PR otherwise workaround https://github.com/minkphp/MinkSelenium2Driver/commit/cfb81e9e821b5a287069f3e3b83b5d744030f3c3 is needed and the native syn.js/better mapping cannot be used
here is an example from Firefox console on real keyboard presses:
notice the keyCode and charCode is set depending on the keyPress vs keyUp/keyDown event types
same test update is proposed also in https://github.com/minkphp/driver-testsuite/pull/42, but this PR does not propose other test changes for easier review

Fix obsolete event.which for key testing

---

tests/Basic/BasicAuthTest.php
tests/Basic/BestPracticesTest.php
tests/Basic/ContentTest.php
tests/Basic/CookieTest.php
tests/Basic/ErrorHandlingTest.php
tests/Basic/HeaderTest.php
tests/Basic/IFrameTest.php
tests/Basic/NavigationTest.php
tests/Basic/ScreenshotTest.php
tests/Basic/StatusCodeTest.php
tests/Basic/TraversingTest.php
tests/Basic/VisibilityTest.php
tests/Css/HoverTest.php
tests/Form/CheckboxTest.php
tests/Form/GeneralTest.php
tests/Form/Html5Test.php
tests/Form/RadioTest.php
tests/Form/SelectTest.php
tests/Js/ChangeEventTest.php
tests/Js/EventsTest.php
tests/Js/JavascriptEvaluationTest.php
tests/Js/JavascriptTest.php
tests/Js/WindowTest.php

This PR migrates all data providers to be static methods as non-static ones are deprecated in PHPUnit 9.6 and unsupported in PHPUnit 10.

Migrate to static data-providers

---

tests/Form/Html5Test.php

There are 3 fixes:
1. use https url - just a nice to have to avoid IDE complaints on using unsafe protocol
2. use `14:12` instead of `12:12`; without this change the browser doesn't know if it's AM or PM, causing the form to be invalid and not submittable. Using `14`, causes the browser to correctly guess we're interested in PM.
3. filling the date was the trickiest problem, [since as of now](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#handling_browser_support
), there's no sane way to force a specific date field format. The fix is (ironically) to use the ambiguity behind `1111-11-11` which gives us a valid date no matter what. 🤷

Fix tests failing from format ambiguities

---

tests/TestCase.php

This relies on a feature/hack that is not supported anymore in PHPUnit 10. Drivers should instead skip those tests through the `skipMessage` method of their test config.
Refs #65. Before merging this one, we need to update all drivers. This deprecation makes it easier to see what needs to be updated.

Deprecate marking tests as skipped for unsupported actions

---

http-kernel-fixtures/advanced_form_post.php
web-fixtures/advanced_form_post.php

This transformation of the input is not needed for drivers submitting values properly and could hide invalid implementations.

Remove wrong request transformation

---

tests/Js/EventsTest.php

Hey, the first scenario provided by provideKeyboardEventsModifiers attempts to pass a null to the test method's first argument, defined as a string, causing a TypeError:
https://github.com/minkphp/driver-testsuite/blob/3bee79433f88e78ab696e33cb9a71b26037b4f73/tests/Js/EventsTest.php#L120
https://github.com/minkphp/driver-testsuite/blob/3bee79433f88e78ab696e33cb9a71b26037b4f73/tests/Js/EventsTest.php#L91

Fix TypeError

---

tests/Js/WindowTest.php

Adds a test that ensures that the current window name is one of the available window names.
This scenario is especially useful when we need to handle window handles instead of names.

Add testWindowName

---

http-kernel-fixtures/print_cookies.php

Fixes this failure: https://github.com/minkphp/driver-testsuite/actions/runs/5501534048/jobs/10025187827?pr=75
The `mink_dump` function seems to handle mixed-type values just fine.
While this change is not backward compatible, (e.g. `(int)42` was rendered as `` `42` `` before and now it would be `42`), the tests still passed just fine, so I'm confident that it's not a problem.

Fix phpstan error

---

tests/Form/GeneralTest.php

- replace duplicate tests with data providers
Depends on #81.

Improve GeneralTest

---

tests/Js/WindowTest.php

Main motivation for this: Edge most of the time fails this test because 500x300 is (apparently) too small.
1. I did a small refactor of the JS side, so it's clearer how it behaves (and also reuses the same values).
2. I increased the window size to 640x480 - test is now passing on MSEdge reliably.

Refactor testResizeWindow; increase window size for MSEdge

---

tests/Form/GeneralTest.php
tests/Form/Html5Test.php

The contract of the method says that the argument type is `string|bool|array`. Passing null does not respect the contract. So there is no reason for the driver testsuite to expect drivers to throw a DriverException for this case.
This was introduced in #78 and #79.
I caught this when updating BrowserKitDriver to make those new tests pass, when phpstan told me that the value cannot be `null` and so the `$value === null` condition was always false.

Remove tests enforcing a DriverException for null values in setValue

---

tests/Basic/IFrameTest.php
web-fixtures/iframe.html

Existing tests only cover iframe switching by name. This PR adds these tests:
1. frame switching by an id;
2. frame switching by an index.
See https://github.com/minkphp/Mink/issues/866 (PR 2 of 4)
The PhpStan correctly reports this, but I can't fix it due to the problem described in the above-mentioned issue.
```
Error: Parameter #1 $name of method Behat\Mink\Session::switchToIFrame() expects string|null, int|string given.
```

Added tests to verify, that iframe switching by an id works

---

tests/Js/EventsTest.php

This fix addresses the point here: https://github.com/minkphp/webdriver-classic-driver/pull/6#discussion_r1516674610
Partially duplicates https://github.com/minkphp/driver-testsuite/pull/29 ([here](https://github.com/minkphp/driver-testsuite/pull/29/files#diff-cd4e4a44bb7db8b4d355edbf0deca9b154f6d6f2cce6a2bacb663f3bbb7c1019R81))

Focus element before testing blur

---

tests/Js/JavascriptTest.php
web-fixtures/js_test.html

needed for https://github.com/minkphp/MinkSelenium2Driver/pull/359
discussed in https://github.com/minkphp/MinkSelenium2Driver/pull/359#issuecomment-1280877930

Test drop onto itself and hide when dragging

---

tests/Js/JavascriptTest.php

Corrects PhpStan report on #59, which was merged last week.
```
------ ---------------------------------------------------------------------------------------------------------------- 
Line   tests/Js/JavascriptTest.php                                                                                     
------ ---------------------------------------------------------------------------------------------------------------- 
34     Method Behat\Mink\Tests\Driver\Js\JavascriptTest::testDragDropOntoHiddenItself() has no return type specified.  
------ ---------------------------------------------------------------------------------------------------------------- 
```
P.S.
I'm not sure why, but no GitHub Actions were executed on that PR and therefore PhpStan wasn't able to report this prior to …

Fixed return type of the "testDragDropOntoHiddenItself" test

---

tests/Js/SessionResetTest.php

Related to discussion on the https://github.com/minkphp/webdriver-classic-driver/pull/27 .
The PhpStan failure is unrelated and is fixed in the https://github.com/minkphp/driver-testsuite/pull/95 .

Added test to confirm, that opened windows are closed by the `Session::reset` call

---

web-fixtures/iframe.html

The #87 add test, that verifies frame switching by an ID. However I've just noticed that both frames have only `name` attribute.
This is fixed now.

Corrected a frame test fixture

---

tests/Form/GeneralTest.php

Relates to https://github.com/minkphp/webdriver-classic-driver/issues/10.
Failure is solved by https://github.com/minkphp/driver-testsuite/pull/100.

Test using invalid values for checkbox

---

tests/Js/WindowTest.php

Relates to https://github.com/minkphp/webdriver-classic-driver/issues/10.
Failure is solved by https://github.com/minkphp/driver-testsuite/pull/100.

Test switching to missing window
